.gitignore

Добавил в гитигнор правила для райдера.

chore: rider gitignore

---

Source/Infrastructure/Kysect.Shreks.Seeding/Extensions/RegistrationExtensions.cs

Быстрофикс.
Заметил что я забыл вызвать сохранение данных в методе использования сидеов.

fix: apply seeding

---

.github/workflows/dotnet-build.yml
.github/workflows/sonar-cloud.yml

feat: add dotnet build and sonar ci

---

.github/workflows/dotnet-build.yml

Оказывается, что зря быконул на CI, я просто не увидел ошибку.

hotfix: update ci

---

Source/Domain/Kysect.Shreks.Core/Kysect.Shreks.Core.csproj
Source/Playground/Kysect.Shreks.Playground.Github/Kysect.Shreks.Playground.Github.csproj
Source/Playground/Kysect.Shreks.Playground.Github/Program.cs
Source/Playground/Kysect.Shreks.Playground/Kysect.Shreks.Playground.csproj
Source/Playground/Kysect.Shreks.Playground/Program.cs
Source/Tests/Kysect.Shreks.Tests/Kysect.Shreks.Tests.csproj
Source/Tests/Kysect.Shreks.Tests/Tools/LogInitialization.cs

feat: add serilog and init for it

---

Source/Domain/Kysect.Shreks.Core/Study/Assignment.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Converters/SubmissionsConverter.cs
Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/AssignmentGenerator.cs

add short name for lab

---

Source/Application/Kysect.Shreks.Application.Abstractions/Google/IGoogleTableAccessor.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Google/Models/AssignmentPoints.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Google/Models/CoursePoints.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Google/Models/StudentPoints.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Google/Models/StudentsQueue.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetCoursePointsBySubjectCourse.cs
Source/Application/Kysect.Shreks.Application.Handlers/Google/GetCoursePointsBySubjectCourseHandler.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/PointsSheetComponentFactory.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/QueueSheetComponentFactory.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Segments/AssignmentPointsSegment.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Segments/PointsStudentSegment.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Segments/TotalPointsSegment.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Sheets/PointsSheet.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Sheets/QueueSheet.cs
Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/AssignmentGenerator.cs
Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGenerator.cs
Source/Playground/Kysect.Shreks.Playground.Google/Kysect.Shreks.Playground.Google.csproj
Source/Playground/Kysect.Shreks.Playground.Google/Program.cs
Source/Tests/Kysect.Shreks.Tests/Application/GoogleWorkerTest.cs

В процессе еще немного пофиксил генераторы, надеюсь ок, что это в этом пр

Feat: Course Points Query

---

Source/Application/Kysect.Shreks.Application.Abstractions/Submissions/Commands/UpdateSubmissionPoints.cs
Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionPointsHandler.cs
Source/Domain/Kysect.Shreks.Core/Study/Submission.cs
Source/Domain/Kysect.Shreks.Core/ValueObject/Rating.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Context/ShreksDatabaseContext.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/ValueConverters/RatingValueConverter.cs
Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubmissionGenerator.cs

Refactor: change submission points to rating

---

Source/Application/Kysect.Shreks.Application.Dto/Tables/AssignmentPointsDto.cs
Source/Application/Kysect.Shreks.Application.Handlers/Google/GetCoursePointsBySubjectCourseHandler.cs
Source/Domain/Kysect.Shreks.Core/Study/Submission.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Segments/AssignmentPointsSegment.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Segments/TotalPointsSegment.cs

Я ещё завёл #126, fyi @Mihinator3000

feat: make submission point nullable

---

.github/ISSUE_TEMPLATE/new-command-query-request.md

Не уверен, что нам нужно что-то более сложное. Добавил два хедера - для ввода/вывода и описания самого хендлера, если там какая-то логика будет сложная.

Update issue templates

---

Source/Application/Kysect.Shreks.Application.Dto/Study/SubmissionDto.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
Source/Tests/Kysect.Shreks.Tests/DataAccess/DataAccessTestBase.cs
Source/Tests/Kysect.Shreks.Tests/Mapping/GetCoursePointsBySubjectCourseHandlerTest.cs

По мотивам проблемы с мапингом инициирую написание тестов на мапинг. It isn't much but...

test: add test for failed case with mapping Submission to Dto

---

Source/Application/Kysect.Shreks.Application.Abstractions/Github/Queries/GerUserCourseRole.cs
Source/Application/Kysect.Shreks.Application.Dto/Users/UserCourseRole.cs
Source/Application/Kysect.Shreks.Application.Handlers/Users/GetUserCourseRoleHandler.cs

Кверя для получения роли пользователя

---

Source/Application/Kysect.Shreks.Application.Dto/Study/SubmissionDto.cs
Source/Application/Kysect.Shreks.Application.Handlers/Google/GetCoursePointsBySubjectCourseHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Submissions/CreateSubmissionHandler.cs
Source/Domain/Kysect.Shreks.Core/Queue/Evaluators/AssignmentDeadlineStateEvaluator.cs
Source/Domain/Kysect.Shreks.Core/Queue/Filters/AssignmentGroupFilter.cs
Source/Domain/Kysect.Shreks.Core/Study/Submission.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/SubmissionConfiguration.cs
Source/Infrastructure/Kysect.Shreks.Mapping/Profiles/SubmissionProfile.cs
Source/Infrastructure/Kysect.Shreks.Mapping/Profiles/ValueObjectsProfile.cs
Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubmissionGenerator.cs
Source/Playground/Kysect.Shreks.Playground/Program.cs

Обсуждали, что правильней будет привязывать submissions к group assignment, а не к assignment.
Но у меня опять автомапер умер и я написал мапинг руками =_=.

feat: link submissions to group assignment

---

Source/Application/Kysect.Shreks.Application.Abstractions/Github/Commands/SyncGithubAdminWithMentors.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Github/IOrganizationDetailsProvider.cs
Source/Application/Kysect.Shreks.Application.Handlers/Github/GetSubjectCourseByOrganizationHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Github/SyncGithubAdminWithMentorsHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Kysect.Shreks.Application.Handlers.csproj
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Entities/OrganizationDetailsProvider.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs

Есть ряд сомнительных мест, так что лучше смотреть чем не смотреть.

feat: implement syncing github admins with mentors

---

Source/Application/Kysect.Shreks.Application.Dto/Tables/AssignmentPointsDto.cs
Source/Application/Kysect.Shreks.Application.Handlers/Google/GetCoursePointsBySubjectCourseHandler.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Segments/AssignmentPointsSegment.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Segments/TotalPointsSegment.cs

@Mihinator3000 
На самом деле, там нужно не откатывать, а наоборот логику добить. Ты правильно сказал, что нет смысла создавать AssignmentPointsDto, если нет баллов. А это значит, что в GetAssignmentPoints при просмотре сабмишенов у нас может не быть ни одного оценённого. И мы можем (и должны) просто скипнуть всю группу.

feat: skip unrated submits while printing to table

---

Source/Application/Kysect.Shreks.Application.Abstractions/Github/Commands/AddSubmissionGithubPrAssociation.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Github/Queries/GetCurrentUnratedSubmissionByPrNumber.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Submissions/Commands/CreateOrUpdateSubmission.cs
Source/Application/Kysect.Shreks.Application.Handlers/Github/AddSubmissionGithubPrAssociationHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Github/GetCurrentUnratedSumbissionByPrNumberHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Github/GetSubjectCourseByOrganizationHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Submissions/CreateOrUpdateSubmissionHandler.cs
Source/Domain/Kysect.Shreks.Core/Study/Submission.cs

Close #133
Пришлось отбранчиться от ветки @darksidersstrife, потому что он там добавлял SubmissionAssociation, которая нужна была тут. Поэтому в пулл-реквест попали не мои коммиты (когда та ветка вмёрджится в мастер, они пропадут).

Creating or updating submission logic

---

Source/Application/Kysect.Shreks.Application.Handlers/Submissions/CreateOrUpdateSubmissionHandler.cs

Приношу свои извенения, я вчера проиграл в ветки, когда мы разгребали таски. Пробежался ещё раз. Выглядит так, что везде всё есть, кроме команды, которую добавили сегодня.
close #140

fix: add missed table sync in new command

---

Source/Application/Kysect.Shreks.Application.Handlers/Google/GetCoursePointsBySubjectCourseHandler.cs

* Closes #111 
Пинайте меня ногами

Add deadline policy usage in get points handler

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
Source/Kysect.Shreks.WebApi/Program.cs
Source/Kysect.Shreks.WebApi/TestEnvConfiguration.cs
Source/Kysect.Shreks.WebApi/appsettings.json
Source/Playground/Kysect.Shreks.Playground.Github/Kysect.Shreks.Playground.Github.csproj
Source/Playground/Kysect.Shreks.Playground.Github/Program.cs
Source/Playground/Kysect.Shreks.Playground.Google/Program.cs

Добавил dummy реализацию, чтобы была возможность запустить чисто команды потыкать гитхабовские.

feat: add dummy google integration

---

Source/Domain/Kysect.Shreks.Core/ValueObject/Points.cs

Close #132
Кажется даже ИСУ не саппортит >2 знаков, так что не вижу проблемы добавить это прям в тип баллов

Округление баллов до 2 знаков

---

Source/Application/Kysect.Shreks.Application.Abstractions/Github/Commands/CreateOrUpdateGithubSubmission.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Github/Queries/GetCurrentUnratedSubmissionByPrNumber.cs
Source/Application/Kysect.Shreks.Application.Commands/Commands/RateCommand.cs
Source/Application/Kysect.Shreks.Application.Dto/Github/GithubPullRequestDescriptor.cs
Source/Application/Kysect.Shreks.Application.Dto/Study/SubmissionDto.cs
Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Github/GetCurrentUnratedSumbissionByPrNumberHandler.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/ContextFactory/IssueCommentContextFactory.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs

Попытался местами улучшить логирование и унифицирвоать процесс. Наткнулся на то, что не резолвится нормально branch name для комментов, а хотелось бы. Завёл #168.

feat: enhance github processor, improve logging and responses

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs

Проблема аналогичная с Google worker.

fix: create scoping for github worker

---

Source/Domain/Kysect.Shreks.Core/Models/SubmissionState.cs
Source/Domain/Kysect.Shreks.Core/Queue/Filters/AssignmentGroupFilter.cs
Source/Domain/Kysect.Shreks.Core/Queue/Filters/GroupQueueFilter.cs
Source/Domain/Kysect.Shreks.Core/Queue/Filters/SubmissionQueueFilter.cs
Source/Domain/Kysect.Shreks.Core/Queue/Filters/SubmissionStateFilter.cs
Source/Domain/Kysect.Shreks.Core/Queue/SubmissionQueue.cs
Source/Domain/Kysect.Shreks.Core/Study/Assignment.cs
Source/Domain/Kysect.Shreks.Core/Study/StudentGroup.cs
Source/Domain/Kysect.Shreks.Core/Submissions/Submission.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/QueueFiltersConfiguration.cs

feat: submission state

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs
Source/Kysect.Shreks.WebApi/Program.cs

close #6 
Добился генерации и баллов и очереди. Работает с коробки!

fix: use pr num instead of id, add simple seeding for demo, add db deleting

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Tools/SheetManagementService.cs

Пару раз словил эксепшен, что в таблице не хватает строк. Мне кажется логичнее будет сразу с запасом сделать, тем более на перфоманс это влиять не должно

Fix: additional table rows

---

Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
Source/Domain/Kysect.Shreks.Core/Queue/Evaluators/AssignmentDeadlineStateEvaluator.cs
Source/Domain/Kysect.Shreks.Core/Tools/Calendar.cs
Source/Playground/Kysect.Shreks.Playground/Program.cs

feat: calendar

---

Source/Application/Kysect.Shreks.Application.Dto/Study/AssignmentDto.cs
Source/Domain/Kysect.Shreks.Core/Study/Assignment.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Segments/AssignmentPointsSegment.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Sheets/PointsSheet.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Tools/SheetManagementService.cs
Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/AssignmentGenerator.cs
Source/Playground/Kysect.Shreks.Playground/Program.cs

Если честно не знаю, как добавить нормальную проверку на номер ассайнмента, и надо ли

Feat: Assignment order

---

Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/AssignmentConfiguration.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/SubjectCourses/GithubSubjectCourseAssociationConfiguration.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/SubjectCourses/SubjectCourseAssociationConfiguration.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/SubjectCourses/SubjectCourseConfiguration.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Submissions/SubmissionAssociationConfiguration.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Users/GithubUserAssociationConfiguration.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Users/IsuUserAssociationConfiguration.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Users/UserAssociationConfiguration.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Users/UserConfiguration.cs
Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/SubjectCourseAssociations/SubjectCourseAssociationGenerator.cs

* Closes #208 
Генератор был изменён т.к. Commerce.Product генерирует не уникальные имена

Database unique constraints

---

Docs/TechDocs/Readme.md

Add GitHub OAuth config guide

---

Source/Infrastructure/Kysect.Shreks.DataAccess/Configurations/Queue/QueueFiltersConfiguration.cs

fix: submission queue filter discriminator

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookCommentSender.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs

Feat: change submission state when pr is closed and reopened

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookCommentSender.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs

Feat: add pull request event processing

---

Source/Application/Kysect.Shreks.Application.Abstractions/Study/Commands/CreateAssignment.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Study/Commands/UpdateAssignmentPoints.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Study/Queries/GetAssignmentById.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Study/Queries/GetAssignmentsBySubjectCourse.cs
Source/Application/Kysect.Shreks.Application.Dto/Study/AssignmentDto.cs
Source/Application/Kysect.Shreks.Application.Handlers/Study/Assignments/CreateAssignmentHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Study/Assignments/GetAssignmentByIdHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Study/Assignments/GetAssignmentsBySubjectCourseHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Study/Assignments/UpdateAssignmentPointsHandler.cs
Source/Infrastructure/Kysect.Shreks.Mapping/Profiles/StudyProfile.cs
Source/Kysect.Shreks.WebApi/Controllers/AssignmentController.cs
Source/Kysect.Shreks.WebApi/Models/CreateAssignmentRequest.cs

Add assignment CRU

---

Source/Application/Kysect.Shreks.Application.Abstractions/Study/Commands/CreateGroupAssignment.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Study/Commands/UpdateGroupAssignmentDeadline.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Study/Queries/GetGroupAssignments.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Study/Queries/GetGroupAssignmentsByStudyGroupId.cs
Source/Application/Kysect.Shreks.Application.Dto/Study/GroupAssignmentDto.cs
Source/Application/Kysect.Shreks.Application.Handlers/Study/CreateGroupAssignmentHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Study/GetGroupAssignments.cs
Source/Application/Kysect.Shreks.Application.Handlers/Study/GetGroupAssignmentsByStudyGroupIdHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Study/UpdateGroupAssignmentDeadlineHandler.cs
Source/Infrastructure/Kysect.Shreks.Mapping/Profiles/StudyProfile.cs
Source/Kysect.Shreks.WebApi/Controllers/GroupAssignmentController.cs
Source/Tests/Kysect.Shreks.Tests/Mapping/MappingTest.cs

Add GroupAssignment crud-operations

---

Source/Application/Kysect.Shreks.Application.Abstractions/Submissions/Commands/UpdateSubmissionDate.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Submissions/Commands/UpdateSubmissionPoints.cs
Source/Application/Kysect.Shreks.Application.Commands/Commands/RateCommand.cs
Source/Application/Kysect.Shreks.Application.Commands/Commands/UpdateCommand.cs
Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionPointsHandler.cs

feat: add validation for user commands

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookCommentSender.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs
Source/Kysect.Shreks.WebApi/Program.cs

review processing bug fix

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs

fix: do not send response on unsupported review event

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookCommentSender.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs

Fix: review processing reactions bug

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs

Fix: comment action processing

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs

Fix: add submission state changed notification

---

Source/Application/Kysect.Shreks.Application.Abstractions/Github/Queries/GetLastSubmissionByPr.cs
Source/Application/Kysect.Shreks.Application.Commands/Commands/HelpCommand.cs
Source/Application/Kysect.Shreks.Application.Handlers/Github/GetCurrentUnratedSumbissionByPrNumberHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Github/GetLastSubmissionByPrHandler.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs

Feat: add second review processing

---

Source/Application/Kysect.Shreks.Application/Factory/SubmissionFactory.cs

fix: CreateGithubSubmissionAsync now can be called by mentors.

---

Source/Application/Kysect.Shreks.Application.Commands/Parsers/ShreksCommandParser.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookCommentSender.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs

fix: Fixed various typos in error messages

---

Source/Application/Kysect.Shreks.Application.Handlers/Google/GetCoursePointsBySubjectCourseHandler.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableUpdateWorker.cs
Source/Tests/Kysect.Shreks.Tests/Application/GetCoursePointsBySubjectCourseHandlerTest.cs

Improved logging for #100
+ Added performance measurement

Improved logging for GoogleTableUpdateWorker

---

Source/Application/Kysect.Shreks.Application.Handlers/Study/GetSubjectCoursesHandler.cs
Source/Infrastructure/Kysect.Shreks.Mapping/Profiles/SubjectCourseProfile.cs

fix: subject course get 500

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Tables/LabsTable.cs

Наверное не самое лучшее решение, но зато таблицу не придется перерисовывать на обновлении.
(При удаление студентов или лаб, на краях будут оставаться заполненные ячейки, это не пофикшено)

Fix: rewrite old points

---

Source/Kysect.Shreks.WebApi/Controllers/GroupAssignmentController.cs

Fix: group assignment deadline

---

Source/Application/Kysect.Shreks.Application.GithubWorkflow.Abstractions/IGithubUserProvider.cs
Source/Application/Kysect.Shreks.Application.Handlers/Github/AddGithubUserAssociationHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Github/SyncGithubAdminWithMentorsHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Users/UpdateUserGithubUsernameHandler.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Providers/GithubUserProvider.cs

Add check for GitHub user existence

---

Source/Application/Kysect.Shreks.Application.Abstractions/Study/Commands/CreateSubjectCourse.cs
Source/Application/Kysect.Shreks.Application.Dto/Study/SubjectCourseDto.cs
Source/Application/Kysect.Shreks.Application.Dto/Study/SubmissionStateWorkflowTypeDto.cs
Source/Application/Kysect.Shreks.Application.GithubWorkflow/ShreksWebhookEventProcessor.cs
Source/Application/Kysect.Shreks.Application.GithubWorkflow/SubmissionStateMachines/GithubSubmissionStateMachineFactory.cs
Source/Application/Kysect.Shreks.Application.Handlers/Study/CreateSubjectCourseHandler.cs
Source/Application/Kysect.Shreks.Application/Factories/SubjectCourseDtoFactory.cs
Source/Domain/Kysect.Shreks.Core/Study/SubjectCourse.cs
Source/Domain/Kysect.Shreks.Core/SubmissionStateWorkflows/SubmissionStateWorkflowType.cs
Source/Infrastructure/Kysect.Shreks.Mapping/Profiles/ValueObjectsProfile.cs
Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGenerator.cs
Source/Kysect.Shreks.WebApi/Controllers/SubjectCourseController.cs

feat: add workflow type

---

Source/Application/Kysect.Shreks.Application.GithubWorkflow/SubmissionStateMachines/GithubSubmissionStateMachineFactory.cs
Source/Application/Kysect.Shreks.Application.GithubWorkflow/SubmissionStateMachines/ReviewWithDefenseGithubSubmissionStateMachine.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Migrations/20220915180822_Subject-workflow-type-added.Designer.cs
Source/Infrastructure/Kysect.Shreks.DataAccess/Migrations/20220915180822_Subject-workflow-type-added.cs

Реализация получилась в итоге с большим количестом вопросов. Очень много нужно обсуждать с пользователями, как мне кажется. Предлагаю выкатить и получить фидбек, а потом делать хорошое решение. Сейчас главное закрывать требование пользователей.

feat: review with defence workflow

---

Source/Application/Kysect.Shreks.Application.Dto/Github/GithubPullRequestDescriptor.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Helpers/GithubRepositoryLoggerExtensions.cs

Add pr number in logger prefix

---

Docs/TechDocs/GithubSetup.md
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Client/IServiceOrganizationGithubClientProvider.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Client/ServiceOrganizationGithubClientProvider.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Helpers/GithubAppConfiguration.cs
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Providers/GithubUserProvider.cs

Use service organization client instead of app client

---

Source/Application/Kysect.Shreks.Application.Commands/Commands/UpdateCommand.cs
Source/Domain/Kysect.Shreks.Core/Tools/RuCultureDate.cs

fix: parse date with ru local

---

Source/Application/Kysect.Shreks.Application.Commands/Commands/RateCommand.cs
Source/Application/Kysect.Shreks.Application.Commands/Processors/SubmissionService.cs
Source/Application/Kysect.Shreks.Application.GithubWorkflow/SubmissionStateMachines/ReviewWithDefenseGithubSubmissionStateMachine.cs
Source/Application/Kysect.Shreks.Application/ISubmissionService.cs
Source/Domain/Kysect.Shreks.Core/Submissions/Submission.cs
Source/Domain/Kysect.Shreks.Core/Tools/SpbDateTime.cs

Теперь поддерживается нативно перевод в Reviewed.
В целом, оно готово и можно попробовать предложить перейти на этот формат.

fix: review with defense workflow

---

Source/Application/Kysect.Shreks.Application.Commands/Processors/SubmissionService.cs
Source/Application/Kysect.Shreks.Application.Dto/Study/SubmissionDto.cs
Source/Application/Kysect.Shreks.Application.Dto/Study/SubmissionRateDto.cs

Теперь не будем писать время в комментах от бота - нам оно не важно.

fix: do not write time in submission date

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Tables/QueueTable.cs

fix: state column width

---

Source/Application/Kysect.Shreks.Application.Abstractions/Google/Commands/UpdateSubjectCourseTable.cs
Source/Application/Kysect.Shreks.Application.Abstractions/Google/Commands/UpdateSubjectGroupQueueSheet.cs
Source/Application/Kysect.Shreks.Application.Handlers/Google/UpdateSubjectCourseTableHandler.cs
Source/Application/Kysect.Shreks.Application.Handlers/Google/UpdateSubjectGroupQueueSheet.cs
Source/Application/Kysect.Shreks.Application.Handlers/Kysect.Shreks.Application.Handlers.csproj

Add force table update commands

---

Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Tables/PointsTable.cs

Хз в чем была ошибка с LookUp, но с `Index`ом ее вроде не возникает

Fix: LookUp formula

---

Source/Application/Kysect.Shreks.Application.Commands/Kysect.Shreks.Application.Commands.csproj
Source/Domain/Kysect.Shreks.Core/Kysect.Shreks.Core.csproj
Source/Tests/Kysect.Shreks.Tests/GithubWorkflow/GithubSubjectCourseAssociationTest.cs
Source/Tests/Kysect.Shreks.Tests/GithubWorkflow/GithubWorkflowTestBase.cs
Source/Tests/Kysect.Shreks.Tests/GithubWorkflow/Tools/GithubApplicationTestContext.cs
Source/Tests/Kysect.Shreks.Tests/GithubWorkflow/Tools/GithubApplicationTestContextGenerator.cs
Source/Tests/Kysect.Shreks.Tests/GithubWorkflow/Tools/TestEventNotifier.cs
Source/Tests/Kysect.Shreks.Tests/Kysect.Shreks.Tests.csproj
Source/Tests/Kysect.Shreks.Tests/Tools/LogInitialization.cs

Начал с малого - написал тест, которые вызывает создание сабмишена и проверяет, что он создан с правильным стейтом. Вторая итерация написания тестов на гитхабовские обработчики.

Test GitHub workflow

---

Source/Application/Kysect.Shreks.Application.GithubWorkflow/PullRequestCommentContextFactory.cs
Source/Application/Kysect.Shreks.Application.GithubWorkflow/Submissions/GithubCommandSubmissionFactory.cs
Source/Application/Kysect.Shreks.Application.GithubWorkflow/Submissions/GithubSubmissionFactory.cs
Source/Application/Kysect.Shreks.Application.GithubWorkflow/Submissions/IGithubSubmissionFactory.cs

fix: create submission command

---

Source/Application/Kysect.Shreks.Application.Commands/Processors/SubmissionService.cs

rate команда через SubmissionService не нормализовала баллы

fix: rate command

---

Source/Application/Kysect.Shreks.Application.Abstractions/Kysect.Shreks.Application.Abstractions.csproj
Source/Application/Kysect.Shreks.Application.Contracts/Kysect.Shreks.Application.Contracts.csproj
Source/Application/Kysect.Shreks.Application.GithubWorkflow.Abstractions/Kysect.Shreks.Application.GithubWorkflow.Abstractions.csproj
Source/Application/Kysect.Shreks.Application.GithubWorkflow/Kysect.Shreks.Application.GithubWorkflow.csproj
Source/Application/Kysect.Shreks.Application.Google/Kysect.Shreks.Application.Google.csproj
Source/Application/Kysect.Shreks.Application.Handlers/Kysect.Shreks.Application.Handlers.csproj
Source/Application/Kysect.Shreks.Application/Kysect.Shreks.Application.csproj
Source/Application/Kysect.Shreks.DataAccess.Abstractions/Kysect.Shreks.DataAccess.Abstractions.csproj
Source/Directory.Packages.props
Source/Domain/Kysect.Shreks.Common/Kysect.Shreks.Common.csproj
Source/Domain/Kysect.Shreks.Core/Kysect.Shreks.Core.csproj
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Kysect.Shreks.Integration.Github.csproj
Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Kysect.Shreks.Integration.Google.csproj
Source/Infrastructure/Kysect.Shreks.DataAccess/Kysect.Shreks.DataAccess.csproj
Source/Infrastructure/Kysect.Shreks.Identity/Kysect.Shreks.Identity.csproj
Source/Infrastructure/Kysect.Shreks.Mapping/Kysect.Shreks.Mapping.csproj
Source/Infrastructure/Kysect.Shreks.Seeding/Kysect.Shreks.Seeding.csproj
Source/Playground/Kysect.Shreks.ApiClientGeneration/Kysect.Shreks.ApiClientGeneration.csproj
Source/Playground/Kysect.Shreks.DataImport/Kysect.Shreks.DataImport.csproj
Source/Playground/Kysect.Shreks.Playground.Github/Kysect.Shreks.Playground.Github.csproj
Source/Playground/Kysect.Shreks.Playground.Google/Kysect.Shreks.Playground.Google.csproj
Source/Playground/Kysect.Shreks.Playground/Kysect.Shreks.Playground.csproj
Source/Presentation/Kysect.Shreks.Commands/Kysect.Shreks.Commands.csproj
Source/Presentation/Kysect.Shreks.Presentation.GitHub/Kysect.Shreks.Presentation.GitHub.csproj
Source/Presentation/Kysect.Shreks.WebApi.Sdk/Kysect.Shreks.WebApi.Sdk.csproj
Source/Presentation/Kysect.Shreks.WebApi/Kysect.Shreks.WebApi.csproj
Source/Presentation/Kysect.Shreks.WebUI.AdminPanel/Kysect.Shreks.WebUI.AdminPanel.csproj
Source/Tests/Kysect.Shreks.Tests.Handlers/Kysect.Shreks.Tests.Handlers.csproj
Source/Tests/Kysect.Shreks.Tests.Services/Kysect.Shreks.Tests.Services.csproj
Source/Tests/Kysect.Shreks.Tests/Kysect.Shreks.Tests.csproj

Central Package Management
